export const GET_ALL_TASK = 'GET_ALL_TASK';
export const GET_ALL_TASK_SUCCESS = 'GET_ALL_TASK_SUCCESS';
export const GET_ALL_TASK_FAILED = 'GET_ALL_TASK_FAILED';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';
